#!/bin/bash
# Get any extra stuff like libcurl

# top dir is one up from this script's dir
topdir=`dirname $BASH_SOURCE[0]`/..

die() { echo >&2 "$1"; exit 1; }

mkdir -p $topdir/extras || die "failed to make extras dir"
cd $topdir/extras

if [ -d iOScURL ]; then
    echo 'Already have libcurl'
else
    url=http://seiryu.home.comcast.net/~seiryu/software/ioscurl-7.40.0.tar.gz
    echo "Getting libcurl from $url"
    curl -O $url || die "failed to download libcurl"
    tar xf `basename $url`
fi
