#!/bin/bash
# Redirect to ldc2 in build/ldc/bin.  Tries with and without iphoneos-
# prefix.

tooldir=`dirname $BASH_SOURCE[0]`
topdir=`cd $tooldir/..; pwd`

case $0 in
    *-ldc2) prog=ldc2;;
    *-ldmd2) prog=ldmd2;;
esac

path="$topdir/build/ldc/bin"
if [ -x "$path/$prog" ]; then
    progpath="$path/$prog"
elif [ -x "$path/iphoneos-$prog" ]; then
    progpath="$path/iphoneos-$prog"
else    
    echo >&2 "$prog or iphoneos-$prog do not seem to be built yet"
    exit 1
fi

exec $progpath "$@"
