#!/bin/bash
# Configure to build LDC with universal libs (druntime/phobos) for
# all iOS archtectures.  Assumes LLVM is already built

# top dir is one up from this script's dir
topdir=`dirname $BASH_SOURCE[0]`/..

# LLVM_ROOT_DIR must be an absolute path for some reason
absolute=`cd $topdir; pwd`
llvmdir="$absolute/build/llvm/Release/"
installdir="$absolute/build/install"

if [ ! -d "$llvmdir" ]; then
    echo "Missing $llvmdir"
    echo 'LLVM does not seem to be built yet'
    exit 1
fi

if [ -f "$topdir/extras/iOScURL/libcurl.a" ]; then
    withcurl=yes
    echo 'Found libcurl, building phobos with std.net.curl, etc.c.curl'
else
    withcurl=no
    echo 'No libcurl, building phobos without std.net.curl, etc.c.curl'
fi

cd $topdir/build/ldc &&
    cmake -DLLVM_ROOT_DIR=$llvmdir \
	  -DWITH_CURL=$withcurl \
	  -DIPHONEOS_ARCHS='all' \
	  -DPROGRAM_PREFIX=iphoneos- \
	  -DCMAKE_INSTALL_PREFIX=$installdir \
	  -DINCLUDE_INSTALL_DIR=$installdir/import ../../ldc


